package edu.ucsb.tb;

import org.ascape.util.vis.ColorFeature;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.ColorConstants;

import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.amp.agf.gef.DefaultFigureProvider;
import org.eclipse.amp.agf.gef.Shapes;

/**
 * <!-- begin-user-doc -->
 * Individual Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb 
 * <!-- end-user-doc -->
 * @generated
 */
public class IndividualStyle2DFigureProvider extends DefaultFigureProvider {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IFigureProvider singleton;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigure getFigure(Object object) {
		IFigure figure = null;
		Color color = null;
		Individual actions = (Individual) object;
		Individual defaultIndividualStyle = actions;
		if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.suseptible) {
			if (figure == null) {
				figure = Shapes.createOval();
			}
			color = ColorConstants.blue;

			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
			}
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
			}
		}
		if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.latent) {
			if (figure == null) {
				figure = Shapes.createOval();
			}
			color = ColorConstants.orange;

			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
			}
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
			}
		}
		if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.active) {
			if (figure == null) {
				figure = Shapes.createOval();
			}
			color = ColorConstants.red;

			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
			}
			if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
			}
		}
		if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment) {
			IFigure markerFigure = Shapes.getMarkerShape(figure, 0);
			color = ColorConstants.green;

			markerFigure.setBackgroundColor(color);
			((Shape) markerFigure).setFill(true);
		}
		if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.nonCompliantClinicalTreatment) {
			IFigure markerFigure = Shapes.getMarkerShape(figure, 0);
			color = ColorConstants.gray;

			markerFigure.setBackgroundColor(color);
			((Shape) markerFigure).setFill(true);
		}
		if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.noTreatment) {
			IFigure markerFigure = Shapes.getMarkerShape(figure, 0);
			color = ColorConstants.black;

			markerFigure.setBackgroundColor(color);
			((Shape) markerFigure).setFill(true);
		}
		return figure;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IFigureProvider getDefault() {
		if (singleton == null) {
			singleton = new IndividualStyle2DFigureProvider();
		}
		return singleton;
	}
}
