package edu.ucsb.tb;

import org.eclipse.draw2d.ColorConstants;
import org.eclipse.draw2d.Graphics;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;

import org.ascape.model.Agent;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

import org.ascape.util.vis.DrawFeature;

/**
 * <!-- begin-user-doc -->
 * Individual Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb 
 * <!-- end-user-doc -->
 * @generated
 */
public class IndividualStyle2DGraphics extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	enum Shapes {
		rectangle, oval, marker
	};

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	Shapes shape = Shapes.rectangle;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {

		HostCell actionsCell = (HostCell) object;
		if (actionsCell.getOccupant() instanceof Individual) {
			Individual actions = (Individual) actionsCell.getOccupant();
			Individual defaultIndividualStyle = actions;
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.suseptible) {
				Color suseptibleColor = ColorConstants.blue;

				g.setForegroundColor(suseptibleColor);
				g.setBackgroundColor(suseptibleColor);
				shape = shape.oval;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					Color hIVPositiveColor = ColorConstants.orange;

					g.setForegroundColor(hIVPositiveColor);
					g.setBackgroundColor(hIVPositiveColor);
					shape = shape.marker;
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					Color hIVNegativeColor = ColorConstants.blue;

					g.setForegroundColor(hIVNegativeColor);
					g.setBackgroundColor(hIVNegativeColor);
					shape = shape.marker;
				}
			}
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.latent) {
				Color latentColor = ColorConstants.orange;

				g.setForegroundColor(latentColor);
				g.setBackgroundColor(latentColor);
				shape = shape.oval;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					Color hIVPositiveColor = ColorConstants.orange;

					g.setForegroundColor(hIVPositiveColor);
					g.setBackgroundColor(hIVPositiveColor);
					shape = shape.marker;
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					Color hIVNegativeColor = ColorConstants.blue;

					g.setForegroundColor(hIVNegativeColor);
					g.setBackgroundColor(hIVNegativeColor);
					shape = shape.marker;
				}
			}
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.active) {
				Color activeColor = ColorConstants.red;

				g.setForegroundColor(activeColor);
				g.setBackgroundColor(activeColor);
				shape = shape.oval;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					Color hIVPositiveColor = ColorConstants.orange;

					g.setForegroundColor(hIVPositiveColor);
					g.setBackgroundColor(hIVPositiveColor);
					shape = shape.marker;
				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					Color hIVNegativeColor = ColorConstants.blue;

					g.setForegroundColor(hIVNegativeColor);
					g.setBackgroundColor(hIVNegativeColor);
					shape = shape.marker;
				}
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment) {
				Color clinicalColor = ColorConstants.green;

				g.setForegroundColor(clinicalColor);
				g.setBackgroundColor(clinicalColor);
				shape = shape.marker;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.nonCompliantClinicalTreatment) {
				Color nonComplianceColor = ColorConstants.gray;

				g.setForegroundColor(nonComplianceColor);
				g.setBackgroundColor(nonComplianceColor);
				shape = shape.marker;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.noTreatment) {
				Color noTreatmentColor = ColorConstants.black;

				g.setForegroundColor(noTreatmentColor);
				g.setBackgroundColor(noTreatmentColor);
				shape = shape.marker;
				if (shape == Shapes.oval) {
					g.fillOval(0, 0, width, height);
				} else if (shape == Shapes.marker) {
					int d = (int) (width * .25 - 1);
					int d2 = (int) (width * .5 - 1);
					g.fillOval(d, d, d2, d2);
				} else if (shape == Shapes.rectangle) {
					g.fillRectangle(0, 0, width, height);
				}
			}
		}
	}
}
