package edu.ucsb.tb;

import org.ascape.util.vis.ColorFeature;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.ColorConstants;

import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.amp.agf.gef.DefaultFigureProvider;
import org.eclipse.amp.agf.gef.Shapes;

/**
 * <!-- begin-user-doc -->
 * Map Location Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb 
 * <!-- end-user-doc -->
 * @generated
 */
public class MapLocationStyle2DFigureProvider extends DefaultFigureProvider {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IFigureProvider singleton;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigure getFigure(Object object) {
		IFigure figure = null;
		Color color = null;
		MapLocation actions = (MapLocation) object;
		MapLocation defaultTBmodelAgentStyle = actions; /* 
														Evaluation:
														Expression:
														!defaultTBmodelAgentStyle.isActiveSite()
														 */
		/* 
		Evaluation:
		Expression:
		defaultTBmodelAgentStyle.isActiveSite()
		 */
		if (!defaultTBmodelAgentStyle.isActiveSite()) {
			if (figure == null) {
				figure = Shapes.createRectangle();
			}
			color = ColorConstants.black;

			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);
		}
		if (defaultTBmodelAgentStyle.isActiveSite()) {
			if (figure == null) {
				figure = Shapes.createRectangle();
			}
			color = ColorConstants.green;

			figure.setBackgroundColor(color);
			((Shape) figure).setFill(true);
		}
		return figure;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IFigureProvider getDefault() {
		if (singleton == null) {
			singleton = new MapLocationStyle2DFigureProvider();
		}
		return singleton;
	}
}
