package edu.ucsb.tb;

/**
 * <!-- begin-user-doc -->
 * Work Location Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb 
 * <!-- end-user-doc -->
 * @generated
 */
public class WorkLocationStyle2D {

}
