package edu.ucsb.tb;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Individual Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class IndividualStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell actionsCell = (HostCell) object;
		if (actionsCell.getOccupant() instanceof Individual) {
			Individual actions = (Individual) actionsCell.getOccupant();
			Individual defaultIndividualStyle = actions;
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.suseptible) {
				java.awt.Color suseptibleColor = java.awt.Color.BLUE

				;

				g.setColor(suseptibleColor);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					java.awt.Color hIVPositiveColor = java.awt.Color.ORANGE

					;

					g.setColor(hIVPositiveColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					java.awt.Color hIVNegativeColor = java.awt.Color.BLUE

					;

					g.setColor(hIVNegativeColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
			}
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.latent) {
				java.awt.Color latentColor = java.awt.Color.ORANGE

				;

				g.setColor(latentColor);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					java.awt.Color hIVPositiveColor = java.awt.Color.ORANGE

					;

					g.setColor(hIVPositiveColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					java.awt.Color hIVNegativeColor = java.awt.Color.BLUE

					;

					g.setColor(hIVNegativeColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
			}
			if (defaultIndividualStyle.getTBStatus() == TBStatusEnum.active) {
				java.awt.Color activeColor = java.awt.Color.RED

				;

				g.setColor(activeColor);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVPositive) {
					java.awt.Color hIVPositiveColor = java.awt.Color.ORANGE

					;

					g.setColor(hIVPositiveColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
				if (defaultIndividualStyle.getHIVStatus() == HIVStatusEnum.hIVNegative) {
					java.awt.Color hIVNegativeColor = java.awt.Color.BLUE

					;

					g.setColor(hIVNegativeColor);
					java.awt.Shape shapeMarker2 = defaultIndividualStyle
							.shapeMarker2();

				}
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment) {
				java.awt.Color clinicalColor = java.awt.Color.GREEN

				;

				g.setColor(clinicalColor);
				shape = new Ellipse2D.Double(width * .25 - 1, width * .25 - 1,
						width * .5 - 1, width * .5 - 1);
				((Graphics2D) g).fill(shape);
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.nonCompliantClinicalTreatment) {
				java.awt.Color nonComplianceColor = java.awt.Color.GRAY

				;

				g.setColor(nonComplianceColor);
				shape = new Ellipse2D.Double(width * .25 - 1, width * .25 - 1,
						width * .5 - 1, width * .5 - 1);
				((Graphics2D) g).fill(shape);
			}
			if (defaultIndividualStyle.getTreatmentStatus() == TreatmentStatusEnum.noTreatment) {
				java.awt.Color noTreatmentColor = java.awt.Color.BLACK

				;

				g.setColor(noTreatmentColor);
				shape = new Ellipse2D.Double(width * .25 - 1, width * .25 - 1,
						width * .5 - 1, width * .5 - 1);
				((Graphics2D) g).fill(shape);
			}
		}
	}
}
