package edu.ucsb.tb;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

import org.ascape.model.Agent;
import org.ascape.model.Cell;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.ascape.model.LocatedAgent;
import org.ascape.model.Scape;
import org.ascape.model.event.ScapeEvent;
import org.ascape.model.rule.Rule;
import org.ascape.model.rule.ExecuteThenUpdate;
import org.ascape.model.space.CollectionSpace;
import org.ascape.model.space.Coordinate;
import org.ascape.model.space.Coordinate2DDiscrete;
import org.ascape.model.space.Graph;
import org.ascape.model.space.Singleton;
import org.ascape.model.space.Location;
import org.ascape.util.Conditional;

/**
 * <!-- begin-user-doc -->
 * Individual Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class Individual extends CellOccupant {

	/**
	 * <!-- begin-user-doc -->
	 * Where the individual is in the disease cycle.  
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private TBStatusEnum tBStatus = TBStatusEnum.suseptible;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int tBInfectionsPerLifetime = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private TreatmentStatusEnum treatmentStatus = TreatmentStatusEnum.notInfected;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int daysUntilLatent = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int daysUntilRecovered = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int succesfulTreatments = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private HIVStatusEnum hIVStatus = HIVStatusEnum.hIVNegative;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private SmokingEnum smoking = SmokingEnum.nonSmoker;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private GenderEnum gender = GenderEnum.female;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int ageIndex = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int ageRange = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private ComplianceBehaviorEnum complianceBehavior = ComplianceBehaviorEnum.sometimesCompliant;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private double bacterialLoad = 0.0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private HomeSearchEnum homeSearch = HomeSearchEnum.inProgress;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private NutritionEnum nutrition = NutritionEnum.nourished;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private EconomicStatusEnum economicStatus = EconomicStatusEnum.notImprovished;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private double bacterialClearingRate = 0.0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private boolean daytime = false;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private SocialStatusEnum socialStatus = SocialStatusEnum.normal;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int houseID = 0;
	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int workID = 0;

	/**
	 * <!-- begin-user-doc -->
	 * Constructs a new Individual.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Individual() {
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static final long serialVersionUID = 89989998L;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static long nextUniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private long uniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public long getUID() {
		if (uniqueID == 0) {
			uniqueID = nextUniqueID++;
		}
		return uniqueID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Clones the agent, ensuring that a unique id is assigned.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object clone() {
		try {
			Individual clone = (Individual) super.clone();
			clone.uniqueID = 0;
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TBmodel getTBmodel() {
		return (TBmodel) getScape().getScape();
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Color getColor() {
		return Color.LIGHT_GRAY;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Initial Placement Initialization. Executed once at the beginning of each model run.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void initialPlacement() {
		final Object initialLocation = (Object) ((org.ascape.model.space.Discrete) getTBmodel()
				.getVillage().getSpace()).findRandomAvailable();
		if (initialLocation != null) {
			if (getHostScape() != ((Agent) initialLocation).getScape()) {
				die();
				getTBmodel().getIndividualScape().add(this);
			}
			moveTo(((HostCell) initialLocation));
		}
		Conditional individualCopyCondition = new Conditional() {
			private static final long serialVersionUID = 1L;
			public boolean meetsCondition(Object individualCopyCell) {
				individualCopyCell = ((org.ascape.model.HostCell) individualCopyCell)
						.getOccupant();
				if (individualCopyCell instanceof House) {
					return true;
				} else {
					return false;
				}
			}
		};
		final Location individualCopyLocation = ((org.ascape.model.space.Discrete) getTBmodel()
				.getVillage().getSpace()).findNearest(
				((org.ascape.model.CellOccupant) this).getHostCell(),
				individualCopyCondition, false, Double.MAX_VALUE);
		if (individualCopyLocation != null) {
			final House individualCopy = (House) ((org.ascape.model.HostCell) individualCopyLocation)
					.getOccupant();
			if (individualCopy != null) {
				int houseIDAddZero = individualCopy.getHouseID() + 0;

				setHouseID(houseIDAddZero);
			}
		}
		Conditional individualCopyCopyCopyCopyCopyCopyCondition = new Conditional() {
			private static final long serialVersionUID = 1L;
			public boolean meetsCondition(
					Object individualCopyCopyCopyCopyCopyCopyCell) {
				individualCopyCopyCopyCopyCopyCopyCell = ((org.ascape.model.HostCell) individualCopyCopyCopyCopyCopyCopyCell)
						.getOccupant();
				if (individualCopyCopyCopyCopyCopyCopyCell instanceof WorkLocation) {
					return true;
				} else {
					return false;
				}
			}
		};
		final Location individualCopyCopyCopyCopyCopyCopyLocation = ((org.ascape.model.space.Discrete) getTBmodel()
				.getVillage().getSpace()).findNearest(
				((org.ascape.model.CellOccupant) this).getHostCell(),
				individualCopyCopyCopyCopyCopyCopyCondition, false,
				Double.MAX_VALUE);
		if (individualCopyCopyCopyCopyCopyCopyLocation != null) {
			final WorkLocation individualCopyCopyCopyCopyCopyCopy = (WorkLocation) ((org.ascape.model.HostCell) individualCopyCopyCopyCopyCopyCopyLocation)
					.getOccupant();
			if (individualCopyCopyCopyCopyCopyCopy != null) {
				int workIDAddZero = individualCopyCopyCopyCopyCopyCopy
						.getWorkID() + 0;

				setWorkID(workIDAddZero);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Initialize State Initialization. Executed once at the beginning of each model run.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void initializeState() {
		double tBStatusDraw = getRandom().nextDouble();

		double complianceCategoryDraw = getRandom().nextDouble();

		double ageDraw = getRandom().nextDouble();

		double povertyDraw = getRandom().nextDouble();

		double statusDraw = getRandom().nextDouble();

		if (tBStatusDraw < getTBmodel().getPInitialTBPositive()) {
			setTBStatus(TBStatusEnum.latent);
			double activeDraw = getRandom().nextDouble();

			if (activeDraw < getTBmodel().getPInitialActive()) {
				setTBStatus(TBStatusEnum.active);
				setTreatmentStatus(TreatmentStatusEnum.noTreatment);
			}
		}
		if (complianceCategoryDraw < getTBmodel().getPAlwaysCompliantCategory()) {
			setComplianceBehavior(ComplianceBehaviorEnum.alwaysCompliant);
		}
		if (complianceCategoryDraw >= getTBmodel()
				.getPAlwaysCompliantCategory()) {
			double pAlwaysCompliantCategoryAddPSometimesCompliantCategory = getTBmodel()
					.getPAlwaysCompliantCategory()
					+ getTBmodel().getPSometimesCompliantCategory();

			if (complianceCategoryDraw < pAlwaysCompliantCategoryAddPSometimesCompliantCategory) {
				setComplianceBehavior(ComplianceBehaviorEnum.sometimesCompliant);
			}
			if (complianceCategoryDraw >= pAlwaysCompliantCategoryAddPSometimesCompliantCategory) {
				setComplianceBehavior(ComplianceBehaviorEnum.neverCompliant);
			}
		}
		if (ageDraw >= getTBmodel().getPFemale()) {
			setGender(GenderEnum.male);
		} else {
			setGender(GenderEnum.female);
		}
		if (povertyDraw < getTBmodel().getPInitialImpoverished()) {
			setEconomicStatus(EconomicStatusEnum.impoverished);
		}
		if (povertyDraw < getTBmodel().getPInitialMalnourished()) {
			setNutrition(NutritionEnum.malnourished);
		}
		if (statusDraw < getTBmodel().getPHighSocialStatus()) {
			setSocialStatus(SocialStatusEnum.high);
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Individual Rule Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void individualRule() {
		boolean tBStatusIdenticalActive = getTBStatus() == TBStatusEnum.active;

		final Location individualLocation = this;
		if (individualLocation != null) {
			final MapLocation individual = (MapLocation) ((org.ascape.model.CellOccupant) individualLocation)
					.getHostCell();
			if (individual != null) {
				individual.setActiveSite(tBStatusIdenticalActive);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Movement Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void movement() {
		if (!isDaytime() && getTBStatus() != TBStatusEnum.dead) {
			Conditional targetHouseCondition = new Conditional() {
				private static final long serialVersionUID = 1L;
				public boolean meetsCondition(Object targetHouseCell) {
					targetHouseCell = ((org.ascape.model.HostCell) targetHouseCell)
							.getOccupant();
					if (targetHouseCell instanceof House) {
						House targetHouse = (House) targetHouseCell;
						return (targetHouse.getHouseID() == getHouseID());
					} else {
						return false;
					}
				}
			};
			final Location targetHouseLocation = ((org.ascape.model.space.Discrete) getTBmodel()
					.getVillage().getSpace()).findNearest(
					((org.ascape.model.CellOccupant) this).getHostCell(),
					targetHouseCondition, false, Double.MAX_VALUE);
			if (targetHouseLocation != null) {
				final House targetHouse = (House) ((org.ascape.model.HostCell) targetHouseLocation)
						.getOccupant();
				if (targetHouse != null) {
					Conditional nearHouseCondition = new Conditional() {
						private static final long serialVersionUID = 1L;
						public boolean meetsCondition(Object nearHouseCell) {
							nearHouseCell = nearHouseCell;
							if (nearHouseCell instanceof MapLocation) {
								MapLocation nearHouse = (MapLocation) nearHouseCell;
								return (true);
							} else {
								return false;
							}
						}
					};
					final MapLocation nearHouse = (MapLocation) ((org.ascape.model.space.Discrete) targetHouse
							.getTBmodel().getVillage().getSpace())
							.findNearestAvailable(
									((org.ascape.model.CellOccupant) targetHouse)
											.getHostCell(), nearHouseCondition,
									false, Double.MAX_VALUE);
					if (nearHouse != null) {
						if (getHostScape() != ((Agent) nearHouse).getScape()) {
							die();
							getTBmodel().getIndividualScape().add(this);
						}
						moveTo(nearHouse);
						if (getTBStatus() == TBStatusEnum.active) {
							nearHouse
									.setActiveSite(getTBStatus() == TBStatusEnum.active);
						}
					}
				}
			}
		}
		if (isDaytime() && getTBStatus() != TBStatusEnum.dead) {
			Conditional closetoWorkCondition = new Conditional() {
				private static final long serialVersionUID = 1L;
				public boolean meetsCondition(Object closetoWorkCell) {
					closetoWorkCell = ((org.ascape.model.HostCell) closetoWorkCell)
							.getOccupant();
					if (closetoWorkCell instanceof WorkLocation) {
						WorkLocation closetoWork = (WorkLocation) closetoWorkCell;
						return (closetoWork.getWorkID() == getWorkID());
					} else {
						return false;
					}
				}
			};
			final Location closetoWorkLocation = ((org.ascape.model.space.Discrete) getTBmodel()
					.getVillage().getSpace()).findNearest(
					((org.ascape.model.CellOccupant) this).getHostCell(),
					closetoWorkCondition, false, Double.MAX_VALUE);
			if (closetoWorkLocation != null) {
				final WorkLocation closetoWork = (WorkLocation) ((org.ascape.model.HostCell) closetoWorkLocation)
						.getOccupant();
				if (closetoWork != null) {
					Conditional nearWorkCondition = new Conditional() {
						private static final long serialVersionUID = 1L;
						public boolean meetsCondition(Object nearWorkCell) {
							nearWorkCell = nearWorkCell;
							if (nearWorkCell instanceof MapLocation) {
								MapLocation nearWork = (MapLocation) nearWorkCell;
								return (true);
							} else {
								return false;
							}
						}
					};
					final MapLocation nearWork = (MapLocation) ((org.ascape.model.space.Discrete) closetoWork
							.getTBmodel().getVillage().getSpace())
							.findNearestAvailable(
									((org.ascape.model.CellOccupant) closetoWork)
											.getHostCell(), nearWorkCondition,
									false, Double.MAX_VALUE);
					if (nearWork != null) {
						if (getHostScape() != ((Agent) nearWork).getScape()) {
							die();
							getTBmodel().getIndividualScape().add(this);
						}
						moveTo(nearWork);
						if (getTBStatus() == TBStatusEnum.active) {
							nearWork.setActiveSite(getTBStatus() == TBStatusEnum.active);
						}
					}
				}
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Avoidance Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void avoidance() {
		if (getTBStatus() == TBStatusEnum.suseptible && false) {
			Conditional activeMapLocationCondition = new Conditional() {
				private static final long serialVersionUID = 1L;
				public boolean meetsCondition(Object activeMapLocationCell) {
					activeMapLocationCell = activeMapLocationCell;
					if (activeMapLocationCell instanceof MapLocation) {
						MapLocation activeMapLocation = (MapLocation) activeMapLocationCell;
						return (activeMapLocation.isActiveSite());
					} else {
						return false;
					}
				}
			};
			final MapLocation activeMapLocation = (MapLocation) ((org.ascape.model.space.Discrete) getTBmodel()
					.getVillage().getSpace()).findNearest(
					((org.ascape.model.CellOccupant) this).getHostCell(),
					activeMapLocationCondition, false, Double.MAX_VALUE);
			if (activeMapLocation != null) {
				if (getHostScape() != ((Agent) activeMapLocation).getScape()) {
					die();
					getTBmodel().getIndividualScape().add(this);
				}
				moveAway(activeMapLocation);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Disease Process Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void diseaseProcess() {
		if (getTreatmentStatus() != TreatmentStatusEnum.clinicalTreatment
				&& getTBStatus() == TBStatusEnum.latent) {
			double latenttoActiveDraw = getRandom().nextDouble();

			double pActiveTransitionLatent = pActiveTransitionLatent();

			double pActiveTransitionLatentDividePeriodsinYear = pActiveTransitionLatent / 365;

			if (latenttoActiveDraw < pActiveTransitionLatentDividePeriodsinYear) {
				setTBStatus(TBStatusEnum.active);
			}
		}
		if (getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment
				&& getTBStatus() == TBStatusEnum.latent) {
			int daysUntilLatentSubtractUnit = getDaysUntilLatent() - 1;

			int daysUntilRecoveredSubtractUnit = getDaysUntilRecovered() - 1;

			setDaysUntilLatent(daysUntilLatentSubtractUnit);
			if (getDaysUntilLatent() == 0) {
				setTBStatus(TBStatusEnum.latent);
			}
			setDaysUntilRecovered(daysUntilRecoveredSubtractUnit);
			if (getDaysUntilRecovered() == 0) {
				setTBStatus(TBStatusEnum.suseptible);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Calculate P Active Transition Latent.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double pActiveTransitionLatent() {
		double pActiveTransitionLatentFactor = 0.0;

		pActiveTransitionLatentFactor = getTBmodel()
				.getPActiveTransitionLatentFactorBase();
		switch (getHIVStatus()) {
			case hIVNegative :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentHIVNegativeFactor();
				break;
			case hIVPositive :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentHIVPositiveFactor();
				break;
		}
		switch (getSmoking()) {
			case nonSmoker :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentNonSmokerFactor();
				break;
			case smoker :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel().getPActiveTransitionLatentSmokerFactor();
				break;
		}
		switch (getNutrition()) {
			case nourished :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentNourishedFactor();
				break;
			case malnourished :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentMalnourishedFactor();
				break;
		}
		switch (getEconomicStatus()) {
			case notImprovished :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentNotImprovishedFactor();
				break;
			case impoverished :
				pActiveTransitionLatentFactor = pActiveTransitionLatentFactor
						+ getTBmodel()
								.getPActiveTransitionLatentImpoverishedFactor();
				break;
		}
		return pActiveTransitionLatentFactor;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Watch for changes in TB Status.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void watchTBStatus() {
		if (getTBStatus() == TBStatusEnum.latent) {
			setTreatmentStatus(TreatmentStatusEnum.noTreatment);
			int incrementTBInfectionsPerLifetime = getTBInfectionsPerLifetime() + 1;

			setTBInfectionsPerLifetime(incrementTBInfectionsPerLifetime);
		}
		if (getTBStatus() == TBStatusEnum.suseptible) {
			setTreatmentStatus(TreatmentStatusEnum.notInfected);
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Detection Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void detection() {
		if (getTreatmentStatus() == TreatmentStatusEnum.noTreatment) {
			double detectionDraw = getRandom().nextDouble();

			if (getComplianceBehavior() == ComplianceBehaviorEnum.alwaysCompliant
					&& detectionDraw < getTBmodel().getPDetection()) {
				setTreatmentStatus(TreatmentStatusEnum.clinicalTreatment);
			}
			if (getComplianceBehavior() == ComplianceBehaviorEnum.neverCompliant
					&& detectionDraw < getTBmodel().getPDetection()) {
				setTreatmentStatus(TreatmentStatusEnum.nonCompliantClinicalTreatment);
			}
			if (getComplianceBehavior() == ComplianceBehaviorEnum.sometimesCompliant
					&& detectionDraw < getTBmodel().getPDetection()) {
				double complianceDraw = getRandom().nextDouble();

				if (complianceDraw >= getTBmodel()
						.getPSomtimesCompliantwillComply()) {
					setTreatmentStatus(TreatmentStatusEnum.nonCompliantClinicalTreatment);
				}
				if (complianceDraw < getTBmodel()
						.getPSomtimesCompliantwillComply()) {
					setTreatmentStatus(TreatmentStatusEnum.clinicalTreatment);
				}
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Watch for changes in Treatment Status.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void watchTreatmentStatus() {
		if (getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment) {
			int drawDaysuntilRecovered = randomInRange(getTBmodel()
					.getMinDaysClinicalTreatmenttoRecovered(), getTBmodel()
					.getMaxDaysClinicalTreatmenttoRecovered());

			if (getTBStatus() == TBStatusEnum.active
					&& getTreatmentStatus() == TreatmentStatusEnum.clinicalTreatment) {
				int drawDaysuntilLatent = randomInRange(getTBmodel()
						.getMinDaysClinicalTreatmenttoLatent(), getTBmodel()
						.getMaxDaysClinicalTreatmenttoLatent());

				setDaysUntilLatent(drawDaysuntilLatent);
			}
			setDaysUntilRecovered(drawDaysuntilRecovered);
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Derive Succesful Treatments.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getSuccesfulTreatments() {
		if (getTBStatus() != TBStatusEnum.suseptible) {
			return getTBInfectionsPerLifetime() - 1;

		}
		if (getTBStatus() == TBStatusEnum.suseptible) {
			return getTBInfectionsPerLifetime() - 0;

		}
		return 0;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Watch for changes in Gender.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void watchGender() {
		if (getGender() == GenderEnum.male) {
			int randomWeighted_AgeDistributionMale_ = randomWeighted(getTBmodel()
					.getAgeDistributionMale());

			setAgeIndex(randomWeighted_AgeDistributionMale_);
		}
		if (getGender() == GenderEnum.female) {
			int randomWeighted_AgeDistributionFemale_ = randomWeighted(getTBmodel()
					.getAgeDistributionFemale());

			setAgeIndex(randomWeighted_AgeDistributionFemale_);
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Derive Age Range.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getAgeRange() {
		return getAgeIndex() * 5;

	}
	/**
	 * <!-- begin-user-doc -->
	 * Watch for changes in Age Index.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void watchAgeIndex() {
		double hIVDraw = getRandom().nextDouble();

		if (getGender() == GenderEnum.male) {
			double item_HIVPrevalenceMalebyAgeIndexAgeIndex_ = getTBmodel()
					.getHIVPrevalenceMalebyAgeIndex()[getAgeIndex()]

			;

			if (hIVDraw < item_HIVPrevalenceMalebyAgeIndexAgeIndex_) {
				setHIVStatus(HIVStatusEnum.hIVPositive);
			}
		}
		if (getGender() == GenderEnum.male) {
			double item_SmokingPrevelanceMalebyAgeIndexAgeIndex_ = getTBmodel()
					.getSmokingPrevelanceMalebyAgeIndex()[getAgeIndex()]

			;

			double smokingDraw = getRandom().nextDouble();

			if (smokingDraw < item_SmokingPrevelanceMalebyAgeIndexAgeIndex_) {
				setSmoking(SmokingEnum.smoker);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Immune Response Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void immuneResponse() {
		if (getTBStatus() == TBStatusEnum.suseptible) {
			double bacterialLoadSubtractBacterialClearingRate = getBacterialLoad()
					- getBacterialClearingRate();

			double maximum_BacterialLoadSubtractBacterialClearingRateZero_ = java.lang.Math
					.max(bacterialLoadSubtractBacterialClearingRate, 0)

			;

			setBacterialLoad(maximum_BacterialLoadSubtractBacterialClearingRateZero_);
			if (getBacterialLoad() > getTBmodel()
					.getBacterialLoadInfectionThreshold()) {
				setTBStatus(TBStatusEnum.latent);
			}
		}
		if (getTBStatus() != TBStatusEnum.suseptible) {
			setBacterialLoad(getTBmodel().getBacterialLoadInfectionThreshold());
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Death Process Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void deathProcess() {
		if (getTBStatus() == TBStatusEnum.active) {
			double randomUnit = getRandom().nextDouble();

			double tBActiveDeathRateperYearDividePeriodsinYear = getTBmodel()
					.getTBActiveDeathRateperYear() / 365;

			if (randomUnit < tBActiveDeathRateperYearDividePeriodsinYear) {
				setTBStatus(TBStatusEnum.dead);
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Transmit Rule. Executed every period.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void transmit() {
		if (getTBStatus() == TBStatusEnum.active) {
			Conditional neighboringIndividualsCondition = new Conditional() {
				private static final long serialVersionUID = 1L;
				public boolean meetsCondition(Object neighboringIndividualsCell) {
					if (neighboringIndividualsCell instanceof Individual) {
						return true;
					} else {
						return false;
					}
				}
			};
			final Individual neighboringIndividuals = (Individual) ((org.ascape.model.space.Discrete) getTBmodel()
					.getVillage().getSpace()).findRandomNeighbor(this,
					neighboringIndividualsCondition);
			if (neighboringIndividuals != null) {
				if (neighboringIndividuals.getTBStatus() == TBStatusEnum.suseptible) {
					double bacterialLoadAddActiveBacterialTransmissionRate = neighboringIndividuals
							.getBacterialLoad()
							+ getTBmodel().getActiveBacterialTransmissionRate();

					neighboringIndividuals
							.setBacterialLoad(bacterialLoadAddActiveBacterialTransmissionRate);
				}
			}
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Derive Bacterial Clearing Rate.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double getBacterialClearingRate() {
		double immuneClearing = immuneClearing();

		return immuneClearing + 0;

	}
	/**
	 * <!-- begin-user-doc -->
	 * Calculate Immune Clearing.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double immuneClearing() {
		double immuneClearingFactor = 0.0;

		immuneClearingFactor = getTBmodel().getImmuneClearingFactorBase();
		switch (getHIVStatus()) {
			case hIVNegative :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingHIVNegativeFactor();
				break;
			case hIVPositive :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingHIVPositiveFactor();
				break;
		}
		switch (getSmoking()) {
			case nonSmoker :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingNonSmokerFactor();
				break;
			case smoker :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingSmokerFactor();
				break;
		}
		switch (getNutrition()) {
			case nourished :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingNourishedFactor();
				break;
			case malnourished :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingMalnourishedFactor();
				break;
		}
		switch (getEconomicStatus()) {
			case notImprovished :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingNotImprovishedFactor();
				break;
			case impoverished :
				immuneClearingFactor = immuneClearingFactor
						+ getTBmodel().getImmuneClearingImpoverishedFactor();
				break;
		}
		return immuneClearingFactor;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Derive Daytime.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isDaytime() {
		int now = getScape().getPeriod();

		int nowModuloPeriodsinDay = now % getTBmodel().getPeriodsinDay();

		return nowModuloPeriodsinDay == 0;

	}
	/**
	 * <!-- begin-user-doc -->
	 * An indexed value weighted against a probability distribution. The total probability must sum to 1.0. For example, an input of {.1,.2,.7} under a uniform distribution would would have 10% probability of producing "0" , 20%  for "1" and 70% for "2". This function can then be used with Item to return a biased result from another list.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int randomWeighted(double[] weights) {
		double scalarDraw = getRandom().nextDouble();
		double currentPortion = 0.0;
		for (int i = 0; currentPortion <= 1.0 && i < weights.length; i++) {
			currentPortion += weights[i];
			if (scalarDraw < currentPortion) {
				return i;
			}
		}
		System.out.println("WARNING: Weights do not add to 1.0: "
				+ currentPortion + ". Using final index value.");
		return weights.length - 1;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Gets the TB Status property for Individual.
	 * @return Where the individual is in the disease cycle.  
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TBStatusEnum getTBStatus() {
		return tBStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the TB Status property for Individual.
	 * Where the individual is in the disease cycle.  
	 * @param _tBStatus the new TB Status value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTBStatus(TBStatusEnum _tBStatus) {
		tBStatus = _tBStatus;
		watchTBStatus();
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the TB Infections Per Lifetime property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getTBInfectionsPerLifetime() {
		return tBInfectionsPerLifetime;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the TB Infections Per Lifetime property for Individual.
	 * 
	 * @param _tBInfectionsPerLifetime the new TB Infections Per Lifetime value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTBInfectionsPerLifetime(int _tBInfectionsPerLifetime) {
		tBInfectionsPerLifetime = _tBInfectionsPerLifetime;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Treatment Status property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TreatmentStatusEnum getTreatmentStatus() {
		return treatmentStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Treatment Status property for Individual.
	 * 
	 * @param _treatmentStatus the new Treatment Status value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTreatmentStatus(TreatmentStatusEnum _treatmentStatus) {
		treatmentStatus = _treatmentStatus;
		watchTreatmentStatus();
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Days Until Latent property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getDaysUntilLatent() {
		return daysUntilLatent;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Days Until Latent property for Individual.
	 * 
	 * @param _daysUntilLatent the new Days Until Latent value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setDaysUntilLatent(int _daysUntilLatent) {
		daysUntilLatent = _daysUntilLatent;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Days Until Recovered property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getDaysUntilRecovered() {
		return daysUntilRecovered;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Days Until Recovered property for Individual.
	 * 
	 * @param _daysUntilRecovered the new Days Until Recovered value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setDaysUntilRecovered(int _daysUntilRecovered) {
		daysUntilRecovered = _daysUntilRecovered;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the HIV Status property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public HIVStatusEnum getHIVStatus() {
		return hIVStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the HIV Status property for Individual.
	 * 
	 * @param _hIVStatus the new HIV Status value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setHIVStatus(HIVStatusEnum _hIVStatus) {
		hIVStatus = _hIVStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Smoking property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SmokingEnum getSmoking() {
		return smoking;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Smoking property for Individual.
	 * 
	 * @param _smoking the new Smoking value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setSmoking(SmokingEnum _smoking) {
		smoking = _smoking;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Gender property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GenderEnum getGender() {
		return gender;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Gender property for Individual.
	 * 
	 * @param _gender the new Gender value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGender(GenderEnum _gender) {
		gender = _gender;
		watchGender();
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Age Index property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getAgeIndex() {
		return ageIndex;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Age Index property for Individual.
	 * 
	 * @param _ageIndex the new Age Index value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setAgeIndex(int _ageIndex) {
		ageIndex = _ageIndex;
		watchAgeIndex();
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Compliance Behavior property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComplianceBehaviorEnum getComplianceBehavior() {
		return complianceBehavior;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Compliance Behavior property for Individual.
	 * 
	 * @param _complianceBehavior the new Compliance Behavior value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setComplianceBehavior(ComplianceBehaviorEnum _complianceBehavior) {
		complianceBehavior = _complianceBehavior;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Bacterial Load property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double getBacterialLoad() {
		return bacterialLoad;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Bacterial Load property for Individual.
	 * 
	 * @param _bacterialLoad the new Bacterial Load value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setBacterialLoad(double _bacterialLoad) {
		bacterialLoad = _bacterialLoad;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Home Search property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public HomeSearchEnum getHomeSearch() {
		return homeSearch;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Home Search property for Individual.
	 * 
	 * @param _homeSearch the new Home Search value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setHomeSearch(HomeSearchEnum _homeSearch) {
		homeSearch = _homeSearch;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Nutrition property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NutritionEnum getNutrition() {
		return nutrition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Nutrition property for Individual.
	 * 
	 * @param _nutrition the new Nutrition value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setNutrition(NutritionEnum _nutrition) {
		nutrition = _nutrition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Economic Status property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EconomicStatusEnum getEconomicStatus() {
		return economicStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Economic Status property for Individual.
	 * 
	 * @param _economicStatus the new Economic Status value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setEconomicStatus(EconomicStatusEnum _economicStatus) {
		economicStatus = _economicStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Social Status property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SocialStatusEnum getSocialStatus() {
		return socialStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Social Status property for Individual.
	 * 
	 * @param _socialStatus the new Social Status value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setSocialStatus(SocialStatusEnum _socialStatus) {
		socialStatus = _socialStatus;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the House ID property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getHouseID() {
		return houseID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the House ID property for Individual.
	 * 
	 * @param _houseID the new House ID value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setHouseID(int _houseID) {
		houseID = _houseID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Work ID property for Individual.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getWorkID() {
		return workID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Work ID property for Individual.
	 * 
	 * @param _workID the new Work ID value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setWorkID(int _workID) {
		workID = _workID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getName() {
		if (name == null) {
			return "Individual " + getUID();
		} else {
			return name;
		}
	}
}
