package edu.ucsb.tb;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

import org.ascape.model.Agent;
import org.ascape.model.Cell;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.ascape.model.LocatedAgent;
import org.ascape.model.Scape;
import org.ascape.model.event.ScapeEvent;
import org.ascape.model.rule.Rule;
import org.ascape.model.rule.ExecuteThenUpdate;
import org.ascape.model.space.CollectionSpace;
import org.ascape.model.space.Coordinate;
import org.ascape.model.space.Coordinate2DDiscrete;
import org.ascape.model.space.Graph;
import org.ascape.model.space.Singleton;
import org.ascape.model.space.Location;
import org.ascape.util.Conditional;

/**
 * <!-- begin-user-doc -->
 * Map Location Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class MapLocation extends HostCell {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private double tBBacterialPresense = 0.0;

	/**
	 * <!-- begin-user-doc -->
	 * Constructs a new Map Location.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MapLocation() {
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static final long serialVersionUID = 89989998L;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static long nextUniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private long uniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public long getUID() {
		if (uniqueID == 0) {
			uniqueID = nextUniqueID++;
		}
		return uniqueID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Clones the agent, ensuring that a unique id is assigned.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object clone() {
		try {
			MapLocation clone = (MapLocation) super.clone();
			clone.uniqueID = 0;
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TBmodel getTBmodel() {
		return (TBmodel) getScape().getScape();
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public List getNetwork() {
		return Collections.emptyList();
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private double diffuseTemp;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static final Rule DIFFUSE_RULE = new ExecuteThenUpdate("Diffuse") {

		/**
		 * <!-- begin-user-doc -->
		 * 
		 * <!-- end-user-doc -->
		 * @generated
		 */
		private static final long serialVersionUID = 6846144446402098983L;
		/**
		 * <!-- begin-user-doc -->
		 * Calculate and store diffusion value to neighbors.
		 * 
		 * @param agent the playing agent
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public void execute(Agent agent) {
			MapLocation mapLocation = (MapLocation) agent;
			double valueSum = 0.0f;
			List neighbors = ((Cell) agent).findNeighbors();
			for (Object neighbor : neighbors) {
				MapLocation mapLocationNeighbor = (MapLocation) neighbor;
				valueSum += mapLocationNeighbor.getTBBacterialPresense();
			}
			valueSum -= neighbors.size() * mapLocation.getTBBacterialPresense();
			valueSum /= neighbors.size();
			valueSum = mapLocation.getTBBacterialPresense() + valueSum
					* mapLocation.getTBmodel().getBacterialDiffusionRate();
			valueSum *= 1.0f - mapLocation.getTBmodel().getBacterialDecayRate();
			mapLocation.diffuseTemp = valueSum;
		}
		/**
		 * <!-- begin-user-doc -->
		 * Update diffusion value. Occurs only when all diffusion has been
		 * calculated.
		 * 
		 * @param agent the agent
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public void update(Agent agent) {
			MapLocation mapLocation = (MapLocation) agent;
			mapLocation.setTBBacterialPresense(mapLocation.diffuseTemp);
		}
	};

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Color getColor() {
		return Color.LIGHT_GRAY;
	}
	/**
	 * <!-- begin-user-doc -->
	 * Gets the TB Bacterial Presense property for Map Location.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double getTBBacterialPresense() {
		return tBBacterialPresense;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the TB Bacterial Presense property for Map Location.
	 * 
	 * @param _tBBacterialPresense the new TB Bacterial Presense value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTBBacterialPresense(double _tBBacterialPresense) {
		tBBacterialPresense = _tBBacterialPresense;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getName() {
		if (name == null) {
			return "Map Location " + getUID();
		} else {
			return name;
		}
	}
}
