package edu.ucsb.tb;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Work Location Style 2D Java Implementation.
 * 
 * Generated by AMF for model: TBmodel.metaabm in project: edu.ucsb.tb.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class WorkLocationStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell actionsCell = (HostCell) object;
		if (actionsCell.getOccupant() instanceof WorkLocation) {
			WorkLocation actions = (WorkLocation) actionsCell.getOccupant();
			WorkLocation defaultTBmodelAgentStyle = actions;
			java.awt.Color defaultTBmodelAgentColor = java.awt.Color.WHITE

			;

			g.setColor(defaultTBmodelAgentColor);
			shape = new Rectangle2D.Double(0, 0, width - 1, height - 1);
			((Graphics2D) g).fill(shape);
		}
	}
}
